language: python
python:
  - 2.7
install:
  - pip install git+https://github.com/openlabs/trytond-icecat.git@develop
  - pip install flake8
  - python setup.py install
  - pip install coveralls
script:
  - coverage run setup.py test
  - flake8 .
after_success:
  coveralls
notifications:
  email:
  - ci-notify@openlabs.co.in
